// English Lab — 6-Month Remote-Work English Curriculum (24 weeks)
// Structure per week: t=Persian title, en=English theme,
// v=[english, persian] vocab, p=[english, persian] phrases, d=[speaker, english, persian] dialogue

const WEEKS = [
{ t:"معرفی حرفه‌ای خود", en:"Professional Introductions",
v:[["background","سابقه / پیشینه"],["expertise","تخصص"],["reliability","قابلیت اطمینان"],["responsible for","مسئولِ"],["experience","تجربه"],["field","حوزه / زمینه"],["colleague","همکار"],["role","نقش / سِمَت"]],
p:[["I'm a senior data and maintenance engineer.","من مهندس ارشد داده و نگهداشت هستم."],["I have over ten years of experience in petrochemicals.","بیش از ده سال تجربه در پتروشیمی دارم."],["I specialize in predictive analytics.","تخصص من تحلیل پیش‌بینانه است."],["I'm responsible for maintenance KPI reporting.","مسئول گزارش‌دهی شاخص‌های نگهداشت هستم."],["Nice to meet you. I've heard a lot about your team.","از آشنایی خوشوقتم. درباره تیم شما زیاد شنیده‌ام."],["Let me tell you a bit about my background.","اجازه دهید کمی درباره سابقه‌ام بگویم."]],
d:[["A","Hi, I don't think we've met. I'm Alex from the data team.","سلام، فکر نکنم همدیگر را دیده باشیم. من الکس از تیم داده هستم."],
["B","Nice to meet you, Alex. I'm Sadegh, a maintenance data engineer.","خوشوقتم الکس. من صادق هستم، مهندس داده نگهداشت."],
["A","Great! What do you work on exactly?","عالی! دقیقاً روی چه چیزی کار می‌کنی؟"],
["B","I build dashboards and predictive models for plant equipment.","داشبورد و مدل‌های پیش‌بینانه برای تجهیزات کارخانه می‌سازم."],
["A","That sounds interesting. Which tools do you use?","جالب به نظر می‌رسد. از چه ابزارهایی استفاده می‌کنی؟"],
["B","Mainly Power BI, SQL Server, and Python for analytics.","عمدتاً Power BI، SQL Server و پایتون برای تحلیل."],
["A","We should talk more. Maybe we can collaborate.","باید بیشتر صحبت کنیم. شاید بتوانیم همکاری کنیم."],
["B","Absolutely. Feel free to reach out anytime.","حتماً. هر وقت خواستی در تماس باش."]]},

{ t:"گفت‌وگوی کوتاه و یخ‌شکنی", en:"Small Talk & Icebreakers",
v:[["weekend","آخر هفته"],["weather","آب‌وهوا"],["commute","رفت‌وآمد"],["hobby","سرگرمی"],["by the way","راستی"],["catch up","به‌روز شدن / گپ زدن"],["how's it going","اوضاع چطور است"],["looking forward to","مشتاقِ"]],
p:[["How was your weekend?","آخر هفته‌ات چطور بود؟"],["It's pretty hot here these days.","این روزها اینجا خیلی گرم است."],["How's everything going on your side?","اوضاع آن طرف چطور پیش می‌رود؟"],["By the way, did you watch the match?","راستی، مسابقه را دیدی؟"],["I'm looking forward to the long weekend.","مشتاق تعطیلات آخر هفته طولانی هستم."],["Let's catch up before the meeting starts.","قبل از شروع جلسه کمی گپ بزنیم."]],
d:[["A","Morning! How's it going?","صبح بخیر! اوضاع چطوره؟"],
["B","Not bad, thanks. Busy week, but good. How about you?","بد نیست، ممنون. هفته شلوغی است ولی خوب. تو چطوری؟"],
["A","Same here. How's the weather in Assaluyeh?","منم همینطور. هوای عسلویه چطوره؟"],
["B","Very hot and humid, as usual. Around 45 degrees.","خیلی گرم و شرجی، مثل همیشه. حدود ۴۵ درجه."],
["A","Wow, that's intense! It's raining here in Berlin.","وای، خیلی زیاده! اینجا در برلین باران می‌بارد."],
["B","Lucky you! Anyway, did you have a good weekend?","خوش به حالت! راستی، آخر هفته خوبی داشتی؟"],
["A","Yes, went hiking with friends. Very relaxing.","بله، با دوستان کوهنوردی رفتم. خیلی آرامش‌بخش بود."],
["B","Sounds great. Shall we get started?","عالیه. شروع کنیم؟"]]},

{ t:"اصول تماس تصویری", en:"Video Call Basics",
v:[["mute","بی‌صدا کردن"],["connection","اتصال"],["breaking up","قطع‌ووصل شدن (صدا)"],["share my screen","اشتراک صفحه"],["echo","اکو / پژواک"],["lag","تأخیر"],["rejoin","دوباره وارد شدن"],["can you hear me","صدای من را دارید؟"]],
p:[["Can everyone hear me clearly?","همه صدای من را واضح دارند؟"],["You're on mute, I think.","فکر می‌کنم میکروفونت بسته است."],["Your voice is breaking up a little.","صدایت کمی قطع‌ووصل می‌شود."],["Let me share my screen.","اجازه دهید صفحه‌ام را به اشتراک بگذارم."],["Sorry, my connection dropped. Can you repeat that?","ببخشید، اتصالم قطع شد. می‌شود تکرار کنید؟"],["I'll turn off my camera to improve the connection.","دوربینم را خاموش می‌کنم تا اتصال بهتر شود."]],
d:[["A","Hi Sadegh, can you hear me okay?","سلام صادق، صدای من را خوب داری؟"],
["B","Yes, loud and clear. Can you hear me?","بله، کاملاً واضح. صدای من می‌آید؟"],
["A","There's a slight echo. Are you using headphones?","کمی اکو دارد. از هدفون استفاده می‌کنی؟"],
["B","One second, let me switch to my headset.","یک لحظه، به هدست تغییر می‌دهم."],
["A","Perfect, much better now.","عالی، الان خیلی بهتر شد."],
["B","Great. I'll share my screen and show the dashboard.","خوب. صفحه‌ام را به اشتراک می‌گذارم و داشبورد را نشان می‌دهم."],
["A","We can see it. The charts look clear.","می‌بینیمش. نمودارها واضح هستند."],
["B","If my connection drops, I'll rejoin right away.","اگر اتصالم قطع شد، فوراً دوباره وارد می‌شوم."]]},

{ t:"جلسه استندآپ روزانه", en:"Daily Standup",
v:[["update","به‌روزرسانی / گزارش"],["blocker","مانع"],["in progress","در حال انجام"],["done","انجام‌شده"],["priority","اولویت"],["deadline","مهلت / ددلاین"],["task","وظیفه / کار"],["on track","طبق برنامه"]],
p:[["Yesterday I finished the data migration script.","دیروز اسکریپت مهاجرت داده را تمام کردم."],["Today I'm working on the validation queries.","امروز روی کوئری‌های اعتبارسنجی کار می‌کنم."],["I have a blocker: I need access to the server.","یک مانع دارم: به دسترسی سرور نیاز دارم."],["Everything is on track for Friday's deadline.","همه‌چیز برای مهلت جمعه طبق برنامه است."],["I'll pick up the next task from the backlog.","کار بعدی را از بک‌لاگ برمی‌دارم."],["No blockers on my side.","از طرف من مانعی نیست."]],
d:[["A","Okay team, quick standup. Sadegh, you're first.","خب تیم، استندآپ سریع. صادق، تو اول."],
["B","Sure. Yesterday I completed the asset hierarchy mapping.","حتماً. دیروز نگاشت سلسله‌مراتب تجهیزات را کامل کردم."],
["B","Today I'm writing the integrity checks in SQL.","امروز بررسی‌های یکپارچگی را در SQL می‌نویسم."],
["A","Any blockers?","مانعی هست؟"],
["B","Yes, one. I'm waiting for read access to the production database.","بله، یکی. منتظر دسترسی خواندن به دیتابیس اصلی هستم."],
["A","I'll follow up with IT after this call.","بعد از این تماس با آی‌تی پیگیری می‌کنم."],
["B","Thanks. Otherwise, everything is on track.","ممنون. غیر از آن، همه‌چیز طبق برنامه است."],
["A","Great. Next person, please.","عالی. نفر بعدی، لطفاً."]]},

{ t:"توصیف کار و پروژه‌ها", en:"Describing Your Work",
v:[["pipeline","خط لوله داده / پایپ‌لاین"],["dashboard","داشبورد"],["stakeholder","ذی‌نفع"],["deliverable","خروجی قابل تحویل"],["maintain","نگهداری کردن"],["automate","خودکارسازی کردن"],["improve","بهبود دادن"],["reduce downtime","کاهش زمان توقف"]],
p:[["This dashboard tracks equipment failures in real time.","این داشبورد خرابی تجهیزات را به‌صورت لحظه‌ای رصد می‌کند."],["I automated the monthly reporting process.","فرایند گزارش‌دهی ماهانه را خودکار کردم."],["The goal is to reduce downtime by twenty percent.","هدف کاهش ۲۰ درصدی زمان توقف است."],["We deliver a weekly report to stakeholders.","هفتگی یک گزارش به ذی‌نفعان تحویل می‌دهیم."],["I built the entire pipeline from sensors to dashboard.","کل پایپ‌لاین را از سنسور تا داشبورد ساختم."],["It saves the team about ten hours a week.","حدود ده ساعت در هفته وقت تیم را آزاد می‌کند."]],
d:[["A","Tell me about a project you're proud of.","درباره پروژه‌ای که به آن افتخار می‌کنی بگو."],
["B","Sure. I built a valve reliability reporting system.","حتماً. یک سامانه گزارش قابلیت اطمینان شیرها ساختم."],
["A","What problem did it solve?","چه مشکلی را حل کرد؟"],
["B","Engineers spent days collecting failure data manually.","مهندسان روزها داده خرابی را دستی جمع می‌کردند."],
["B","Now the system generates the full report automatically.","حالا سامانه گزارش کامل را خودکار تولید می‌کند."],
["A","Impressive. What was the impact?","تحسین‌برانگیز است. تأثیرش چه بود؟"],
["B","Reporting time dropped from three days to one hour.","زمان گزارش‌دهی از سه روز به یک ساعت رسید."],
["A","That's a great result to put on your resume.","نتیجه فوق‌العاده‌ای برای رزومه است."]]},

{ t:"اصول ایمیل حرفه‌ای", en:"Email Fundamentals",
v:[["subject line","موضوع ایمیل"],["attached","پیوست‌شده"],["regarding","درباره / در خصوص"],["follow up","پیگیری کردن"],["kind regards","با احترام"],["as discussed","طبق صحبت‌مان"],["please find","لطفاً ملاحظه کنید"],["at your earliest convenience","در اولین فرصت"]],
p:[["I'm writing regarding the migration project.","در خصوص پروژه مهاجرت داده می‌نویسم."],["Please find the report attached.","گزارش پیوست شده است."],["As discussed, I've updated the timeline.","طبق صحبت‌مان، زمان‌بندی را به‌روز کردم."],["Could you review it at your earliest convenience?","می‌توانید در اولین فرصت بررسی‌اش کنید؟"],["I'm following up on my previous email.","ایمیل قبلی‌ام را پیگیری می‌کنم."],["Let me know if you have any questions.","اگر سؤالی داشتید، خبر دهید."]],
d:[["A","Sadegh, did you send the client the KPI report?","صادق، گزارش شاخص‌ها را برای مشتری فرستادی؟"],
["B","Yes, this morning, with the dashboard link attached.","بله، امروز صبح، با لینک داشبورد پیوست."],
["A","Good. What subject line did you use?","خوب. چه موضوعی برای ایمیل نوشتی؟"],
["B","Monthly Maintenance KPI Report — June 2026.","گزارش ماهانه شاخص‌های نگهداشت — ژوئن ۲۰۲۶."],
["A","Clear and specific. Did they reply?","واضح و مشخص. جواب دادند؟"],
["B","Not yet. I'll follow up tomorrow if I hear nothing.","هنوز نه. اگر خبری نشد فردا پیگیری می‌کنم."],
["A","Perfect. Keep the tone polite but direct.","عالی. لحن را مؤدبانه اما مستقیم نگه دار."],
["B","Always. Short sentences, one clear request.","همیشه. جمله‌های کوتاه، یک درخواست روشن."]]},

{ t:"درخواست شفاف‌سازی", en:"Asking for Clarification",
v:[["clarify","شفاف کردن"],["what do you mean by","منظورت از ... چیست"],["in other words","به عبارت دیگر"],["correct me if I'm wrong","اگر اشتباه می‌کنم اصلاحم کن"],["just to confirm","فقط برای اطمینان"],["could you elaborate","می‌شود بیشتر توضیح دهی"],["rephrase","بازگویی کردن"],["make sure","مطمئن شدن"]],
p:[["Sorry, could you say that again more slowly?","ببخشید، می‌شود دوباره و آهسته‌تر بگویید؟"],["What exactly do you mean by 'legacy data'?","دقیقاً منظورتان از «داده قدیمی» چیست؟"],["Just to confirm, the deadline is next Thursday?","فقط برای اطمینان، مهلت پنجشنبه آینده است؟"],["Let me make sure I understood correctly.","بگذارید مطمئن شوم درست فهمیدم."],["Could you elaborate on the second requirement?","می‌شود درباره نیازمندی دوم بیشتر توضیح دهید؟"],["So in other words, we skip the old records?","پس به عبارت دیگر، رکوردهای قدیمی را رد می‌کنیم؟"]],
d:[["A","We need the ETL job to handle the delta loads nightly.","لازم است جاب ETL بارگذاری تغییرات را شبانه انجام دهد."],
["B","Just to confirm, by delta you mean only changed records?","فقط برای اطمینان، منظور از دلتا فقط رکوردهای تغییر‌کرده است؟"],
["A","Exactly, records modified since the last run.","دقیقاً، رکوردهایی که از اجرای قبلی تغییر کرده‌اند."],
["B","Got it. And what do you mean by 'nightly' exactly?","متوجه شدم. و دقیقاً منظور از «شبانه» چیست؟"],
["A","Any time between midnight and 5 AM server time.","هر زمانی بین نیمه‌شب تا ۵ صبح به وقت سرور."],
["B","Correct me if I'm wrong, that's UTC, not local time?","اگر اشتباه می‌کنم بگویید، منظور UTC است نه وقت محلی؟"],
["A","Good catch, yes, UTC.","نکته خوبی بود، بله، UTC."],
["B","Perfect, now everything is clear.","عالی، حالا همه‌چیز روشن است."]]},

{ t:"زمان‌بندی و منطقه‌های زمانی", en:"Scheduling & Time Zones",
v:[["time zone","منطقه زمانی"],["availability","در دسترس بودن"],["reschedule","تغییر زمان دادن"],["overlap","هم‌پوشانی"],["calendar invite","دعوت‌نامه تقویم"],["works for me","برای من مناسب است"],["postpone","به تعویق انداختن"],["tentative","موقت / احتمالی"]],
p:[["What time works for you?","چه ساعتی برایتان مناسب است؟"],["I'm in Iran time, which is UTC plus three thirty.","من به وقت ایران هستم، یعنی UTC مثبت سه‌ونیم."],["Our overlap hours are two to six PM my time.","ساعات هم‌پوشانی ما ۲ تا ۶ عصر به وقت من است."],["Could we reschedule to Wednesday?","می‌شود جلسه را به چهارشنبه منتقل کنیم؟"],["I'll send a calendar invite right after this call.","بلافاصله بعد از این تماس دعوت‌نامه تقویم می‌فرستم."],["Ten AM your time works for me.","ساعت ۱۰ صبح به وقت شما برای من مناسب است."]],
d:[["A","Let's set up a weekly sync. When are you available?","بیایید یک جلسه هفتگی بگذاریم. کی در دسترس هستی؟"],
["B","I'm flexible. What's your time zone?","من انعطاف دارم. منطقه زمانی شما چیست؟"],
["A","Central European Time. And you?","وقت اروپای مرکزی. تو چطور؟"],
["B","Iran Standard Time, UTC plus three thirty.","وقت ایران، UTC مثبت سه‌ونیم."],
["A","So a two-hour difference. How about 2 PM my time?","پس دو ساعت اختلاف. ساعت ۲ عصر به وقت من چطور است؟"],
["B","That's 4 PM for me. Works perfectly.","برای من ۴ عصر می‌شود. کاملاً مناسب است."],
["A","Great, I'll send a recurring invite for Tuesdays.","عالی، دعوت‌نامه تکرارشونده برای سه‌شنبه‌ها می‌فرستم."],
["B","Received. See you next Tuesday then.","دریافت شد. پس سه‌شنبه آینده می‌بینمت."]]},

{ t:"گزارش وضعیت پروژه", en:"Giving Status Updates",
v:[["milestone","نقطه عطف / مرحله کلیدی"],["ahead of schedule","جلوتر از برنامه"],["behind schedule","عقب‌تر از برنامه"],["risk","ریسک"],["estimate","برآورد"],["remaining","باقی‌مانده"],["completed","تکمیل‌شده"],["dependency","وابستگی"]],
p:[["The project is currently on schedule.","پروژه فعلاً طبق برنامه است."],["We've completed eighty percent of the migration.","هشتاد درصد مهاجرت را تکمیل کرده‌ایم."],["There's a risk of delay due to the server upgrade.","به دلیل ارتقای سرور، ریسک تأخیر وجود دارد."],["My estimate is two more weeks of work.","برآورد من دو هفته کار دیگر است."],["The main dependency is the network team's approval.","وابستگی اصلی، تأیید تیم شبکه است."],["I'll have a working version by Friday.","تا جمعه یک نسخه کارا خواهم داشت."]],
d:[["A","Where are we on the Olefin database migration?","وضعیت مهاجرت دیتابیس الفین کجاست؟"],
["B","Good news: we've passed the second milestone.","خبر خوب: از نقطه عطف دوم گذشتیم."],
["B","All six hierarchy levels are mapped and validated.","هر شش سطح سلسله‌مراتب نگاشت و اعتبارسنجی شده‌اند."],
["A","Excellent. Any risks I should know about?","عالی. ریسکی هست که باید بدانم؟"],
["B","One. The tag transformation logic needs a review by operations.","یکی. منطق تبدیل تگ‌ها نیاز به بازبینی تیم بهره‌برداری دارد."],
["A","How much delay could that cause?","چقدر ممکن است تأخیر ایجاد کند؟"],
["B","Worst case, three days. I've already sent them the document.","در بدترین حالت سه روز. مستند را برایشان فرستاده‌ام."],
["A","Good proactive work. Keep me posted.","کار پیش‌دستانه خوبی بود. در جریانم بگذار."]]},

{ t:"اعداد، داده و شاخص‌ها", en:"Numbers, Data & KPIs",
v:[["increase","افزایش"],["decrease","کاهش"],["trend","روند"],["average","میانگین"],["percentage","درصد"],["compared to","در مقایسه با"],["threshold","آستانه"],["outlier","داده پرت"]],
p:[["MTBF increased by fifteen percent this quarter.","MTBF در این فصل ۱۵ درصد افزایش یافت."],["Downtime decreased compared to last month.","زمان توقف نسبت به ماه قبل کاهش یافت."],["The average repair time is six point five hours.","میانگین زمان تعمیر شش‌ونیم ساعت است."],["Vibration levels are above the warning threshold.","سطح ارتعاش بالاتر از آستانه هشدار است."],["We see a clear upward trend in failures.","روند صعودی روشنی در خرابی‌ها می‌بینیم."],["These two points are outliers and should be excluded.","این دو نقطه داده پرت هستند و باید حذف شوند."]],
d:[["A","Walk me through this month's maintenance numbers.","اعداد نگهداشت این ماه را برایم توضیح بده."],
["B","Sure. Overall downtime dropped by twelve percent.","حتماً. زمان توقف کلی ۱۲ درصد کاهش یافت."],
["A","What's driving the improvement?","چه چیزی باعث این بهبود شده؟"],
["B","Mainly the pumps. Their MTBF rose from 90 to 110 days.","عمدتاً پمپ‌ها. MTBF آنها از ۹۰ به ۱۱۰ روز رسید."],
["A","And the compressors?","و کمپرسورها؟"],
["B","Slightly worse. Two unexpected failures pushed MTTR up.","کمی بدتر. دو خرابی غیرمنتظره MTTR را بالا برد."],
["A","Is that a trend or an outlier?","این یک روند است یا داده پرت؟"],
["B","Too early to say. I'll flag it and monitor next month.","برای قضاوت زود است. علامت‌گذاری می‌کنم و ماه بعد رصد می‌کنم."]]},

{ t:"توضیح مشکلات فنی", en:"Explaining Technical Problems",
v:[["issue","مشکل / ایراد"],["root cause","علت ریشه‌ای"],["troubleshoot","عیب‌یابی کردن"],["workaround","راه‌حل موقت"],["reproduce","بازتولید کردن (خطا)"],["symptom","نشانه / علامت"],["crash","از کار افتادن"],["investigate","بررسی کردن"]],
p:[["The report server crashes when we open large reports.","سرور گزارش هنگام باز کردن گزارش‌های بزرگ از کار می‌افتد."],["I can reproduce the issue every time.","هر بار می‌توانم مشکل را بازتولید کنم."],["The root cause was a corrupted index.","علت ریشه‌ای یک ایندکس خراب بود."],["As a workaround, we restart the service nightly.","به‌عنوان راه‌حل موقت، سرویس را شبانه ری‌استارت می‌کنیم."],["I'm still investigating the memory issue.","هنوز در حال بررسی مشکل حافظه هستم."],["The first symptom was slow query performance.","اولین نشانه، کند شدن کوئری‌ها بود."]],
d:[["A","Users say the dashboard is very slow today. Any idea why?","کاربران می‌گویند داشبورد امروز خیلی کند است. می‌دانی چرا؟"],
["B","I noticed it too. I'm troubleshooting right now.","من هم متوجه شدم. الان دارم عیب‌یابی می‌کنم."],
["A","What have you found so far?","تا الان چه چیزی پیدا کردی؟"],
["B","The symptom is high CPU on the SQL server during refresh.","نشانه، مصرف بالای CPU روی سرور SQL هنگام رفرش است."],
["A","Could it be the new dataset we added?","ممکن است دیتاست جدیدی باشد که اضافه کردیم؟"],
["B","Very likely. One query scans the whole failure history table.","خیلی محتمل. یک کوئری کل جدول تاریخچه خرابی را اسکن می‌کند."],
["A","Is there a quick workaround?","راه‌حل موقت سریعی هست؟"],
["B","Yes, I'll add an index now and optimize the query tomorrow.","بله، الان ایندکس اضافه می‌کنم و فردا کوئری را بهینه می‌کنم."]]},

{ t:"موافقت و مخالفت در جلسات", en:"Agreeing & Disagreeing",
v:[["I agree","موافقم"],["I see your point","نظرت را می‌فهمم"],["however","با این حال"],["on the other hand","از طرف دیگر"],["fair point","نکته منصفانه‌ای است"],["I'm not sure about that","درباره‌اش مطمئن نیستم"],["compromise","مصالحه"],["from my perspective","از دید من"]],
p:[["I completely agree with that approach.","کاملاً با آن رویکرد موافقم."],["I see your point, but I have a concern.","نظرت را می‌فهمم، اما یک نگرانی دارم."],["From my perspective, the risk is too high.","از دید من، ریسک خیلی بالاست."],["That's a fair point. Let me think about it.","نکته منصفانه‌ای است. بگذار درباره‌اش فکر کنم."],["I'm not sure that will work with our data volume.","مطمئن نیستم با حجم داده ما جواب بدهد."],["Maybe we can find a compromise.","شاید بتوانیم به یک مصالحه برسیم."]],
d:[["A","I think we should rebuild the whole data model from scratch.","فکر می‌کنم باید کل مدل داده را از صفر بسازیم."],
["B","I see your point, but that could take two months.","نظرت را می‌فهمم، اما ممکن است دو ماه طول بکشد."],
["A","True, but the current model has serious design flaws.","درست است، اما مدل فعلی ایرادهای طراحی جدی دارد."],
["B","I agree the flaws exist. However, we have a deadline.","قبول دارم ایرادها وجود دارند. با این حال، ما مهلت داریم."],
["A","So what do you suggest?","پس پیشنهادت چیست؟"],
["B","A compromise: fix the three worst tables now, rebuild later.","یک مصالحه: سه جدول بدتر را الان اصلاح کنیم، بازسازی بعداً."],
["A","That's actually reasonable. Let's document the plan.","در واقع منطقی است. بیایید برنامه را مستند کنیم."],
["B","Perfect, I'll draft it today.","عالی، امروز پیش‌نویسش را می‌نویسم."]]},

{ t:"ارائه پیشنهاد", en:"Making Suggestions & Proposals",
v:[["suggest","پیشنهاد دادن"],["propose","مطرح کردن / پیشنهاد رسمی"],["alternative","جایگزین"],["benefit","مزیت"],["drawback","اشکال / عیب"],["how about","نظرت درباره ... چیست"],["it might be worth","شاید ارزشش را داشته باشد"],["recommend","توصیه کردن"]],
p:[["I suggest we automate this report with Python.","پیشنهاد می‌کنم این گزارش را با پایتون خودکار کنیم."],["How about using incremental refresh instead?","نظرتان درباره استفاده از رفرش افزایشی چیست؟"],["It might be worth testing on a small dataset first.","شاید ارزشش را داشته باشد اول روی دیتاست کوچک تست کنیم."],["The main benefit is saving five hours per week.","مزیت اصلی، صرفه‌جویی پنج ساعت در هفته است."],["One drawback is the initial setup time.","یک اشکال، زمان راه‌اندازی اولیه است."],["I'd recommend starting with a pilot project.","توصیه می‌کنم با یک پروژه آزمایشی شروع کنیم."]],
d:[["A","Our monthly reporting takes too long. Ideas?","گزارش‌دهی ماهانه ما خیلی طول می‌کشد. ایده‌ای هست؟"],
["B","Yes, I propose we automate it end to end.","بله، پیشنهاد می‌کنم آن را سرتاسر خودکار کنیم."],
["A","How would that work?","چطور کار می‌کند؟"],
["B","A Python script pulls the data, and Power BI refreshes automatically.","یک اسکریپت پایتون داده را می‌کشد و Power BI خودکار رفرش می‌شود."],
["A","What's the benefit in numbers?","مزیتش به عدد چقدر است؟"],
["B","From two days of manual work to about thirty minutes.","از دو روز کار دستی به حدود سی دقیقه."],
["A","Any drawbacks?","اشکالی هم دارد؟"],
["B","We need one week for setup and testing. Worth it, I think.","یک هفته برای راه‌اندازی و تست لازم داریم. به نظرم می‌ارزد."]]},

{ t:"مذاکره بر سر محدوده و مهلت", en:"Negotiating Scope & Deadlines",
v:[["scope","محدوده کار"],["feasible","شدنی / عملی"],["trade-off","بده‌بستان"],["extension","تمدید"],["out of scope","خارج از محدوده"],["realistic","واقع‌بینانه"],["push back","مقاومت کردن / عقب راندن"],["commit to","متعهد شدن به"]],
p:[["That timeline isn't realistic with the current scope.","این زمان‌بندی با محدوده فعلی واقع‌بینانه نیست."],["We can deliver on time if we reduce the scope.","اگر محدوده را کم کنیم، می‌توانیم به‌موقع تحویل دهیم."],["I can commit to the core features by Friday.","می‌توانم به قابلیت‌های اصلی تا جمعه متعهد شوم."],["The mobile version is out of scope for this phase.","نسخه موبایل خارج از محدوده این فاز است."],["Could we get a one-week extension?","می‌شود یک هفته تمدید بگیریم؟"],["There's a trade-off between speed and quality here.","اینجا بده‌بستانی بین سرعت و کیفیت وجود دارد."]],
d:[["A","We need the full dashboard suite in two weeks.","کل مجموعه داشبورد را دو هفته‌ای لازم داریم."],
["B","Honestly, two weeks isn't feasible for all eight dashboards.","صادقانه بگویم، دو هفته برای هر هشت داشبورد شدنی نیست."],
["A","The client is firm on the date.","مشتری روی تاریخ قاطع است."],
["B","Then let's talk scope. Which three dashboards matter most?","پس درباره محدوده صحبت کنیم. کدام سه داشبورد مهم‌ترند؟"],
["A","Failures, costs, and the executive summary.","خرابی‌ها، هزینه‌ها و خلاصه مدیریتی."],
["B","I can commit to those three in two weeks, polished.","می‌توانم به آن سه تا در دو هفته، با کیفیت، متعهد شوم."],
["A","And the rest?","و بقیه؟"],
["B","Two weeks after that. I'll put it in writing today.","دو هفته بعد از آن. امروز مکتوبش می‌کنم."]]},

{ t:"ارتباط با مشتری", en:"Client Communication",
v:[["requirement","نیازمندی"],["expectation","انتظار"],["feedback","بازخورد"],["revision","بازنگری / ویرایش"],["deliver","تحویل دادن"],["clarification","شفاف‌سازی"],["satisfied","راضی"],["scope creep","گسترش بی‌رویه محدوده"]],
p:[["Could you walk me through your requirements?","می‌شود نیازمندی‌هایتان را برایم توضیح دهید؟"],["I want to make sure we're aligned on expectations.","می‌خواهم مطمئن شوم روی انتظارات هم‌نظر هستیم."],["Thanks for the feedback. I'll apply the revisions.","ممنون از بازخورد. بازنگری‌ها را اعمال می‌کنم."],["I'll deliver the first draft by Monday.","پیش‌نویس اول را تا دوشنبه تحویل می‌دهم."],["This new request would expand the original scope.","این درخواست جدید محدوده اولیه را گسترش می‌دهد."],["Are you satisfied with the current design?","از طراحی فعلی راضی هستید؟"]],
d:[["A","We reviewed the dashboard. Overall we like it.","داشبورد را بررسی کردیم. در کل خوشمان آمد."],
["B","Glad to hear that. Any feedback for revisions?","خوشحالم. بازخوردی برای بازنگری هست؟"],
["A","Yes, we'd like a drill-down by equipment type.","بله، می‌خواهیم قابلیت ریزشدن بر اساس نوع تجهیز داشته باشیم."],
["B","That's doable. I'll add it in the next revision.","شدنی است. در بازنگری بعدی اضافه‌اش می‌کنم."],
["A","Also, could we add cost forecasting?","همچنین، می‌شود پیش‌بینی هزینه هم اضافه کنیم؟"],
["B","That's a bigger feature, outside our original agreement.","آن قابلیت بزرگ‌تری است، خارج از توافق اولیه ما."],
["B","I can send you a separate estimate for it.","می‌توانم برآورد جداگانه‌ای برایش بفرستم."],
["A","Fair enough. Please do.","منصفانه است. لطفاً بفرست."]]},

{ t:"ارائه و دموی داشبورد", en:"Presenting a Demo",
v:[["overview","نمای کلی"],["highlight","نکته برجسته / برجسته کردن"],["as you can see","همان‌طور که می‌بینید"],["let's move on to","برویم سراغِ"],["key takeaway","نکته کلیدی"],["filter","فیلتر"],["drill down","ریز شدن در جزئیات"],["wrap up","جمع‌بندی کردن"]],
p:[["Let me give you a quick overview first.","اجازه دهید اول یک نمای کلی بدهم."],["As you can see, failures peak in summer.","همان‌طور که می‌بینید، خرابی‌ها در تابستان اوج می‌گیرند."],["Let's move on to the cost analysis page.","برویم سراغ صفحه تحلیل هزینه."],["You can drill down from plant level to a single pump.","می‌توانید از سطح کارخانه تا یک پمپ ریز شوید."],["The key takeaway is: heat drives most failures.","نکته کلیدی این است: گرما عامل بیشتر خرابی‌هاست."],["Let me wrap up with the next steps.","با گام‌های بعدی جمع‌بندی می‌کنم."]],
d:[["B","Thanks for joining. Today I'll demo the reliability dashboard.","ممنون که آمدید. امروز داشبورد قابلیت اطمینان را دمو می‌دهم."],
["B","First, an overview: this page shows all four production trains.","اول یک نمای کلی: این صفحه هر چهار واحد تولید را نشان می‌دهد."],
["A","What does the red indicator mean?","نشانگر قرمز یعنی چه؟"],
["B","Good question. Red means MTBF is below the target threshold.","سؤال خوبی است. قرمز یعنی MTBF زیر آستانه هدف است."],
["B","Now, as you can see, Train 2 needs attention.","حالا، همان‌طور که می‌بینید، واحد ۲ نیاز به توجه دارد."],
["A","Can we see which equipment is causing it?","می‌توانیم ببینیم کدام تجهیز عاملش است؟"],
["B","Yes, just click here to drill down to the valve level.","بله، فقط اینجا کلیک کنید تا به سطح شیرها ریز شوید."],
["B","Let me wrap up: three actions, listed on the final page.","جمع‌بندی کنم: سه اقدام، در صفحه پایانی فهرست شده‌اند."]]},

{ t:"بازبینی کد و بازخورد فنی", en:"Code Review & Feedback",
v:[["pull request","درخواست ادغام کد"],["refactor","بازآرایی کد"],["readable","خوانا"],["edge case","حالت خاص / مرزی"],["nitpick","ایراد جزئی"],["approve","تأیید کردن"],["naming convention","قرارداد نام‌گذاری"],["looks good to me","به نظرم خوب است"]],
p:[["I left a few comments on your pull request.","چند نظر روی درخواست ادغام کدت گذاشتم."],["This function could be more readable if we split it.","اگر این تابع را بشکنیم، خواناتر می‌شود."],["Have you handled the null value edge case?","حالت خاص مقدار تهی را مدیریت کرده‌ای؟"],["Just a nitpick: the variable naming is inconsistent.","فقط یک ایراد جزئی: نام‌گذاری متغیرها یکدست نیست."],["Looks good to me. Approved.","به نظرم خوب است. تأیید شد."],["Could you add a comment explaining this logic?","می‌شود یک توضیح برای این منطق اضافه کنی؟"]],
d:[["A","I reviewed your migration script. Nice work overall.","اسکریپت مهاجرتت را بررسی کردم. در کل کار خوبی است."],
["B","Thanks! Anything I should change?","ممنون! چیزی هست که باید تغییر دهم؟"],
["A","Two things. First, an edge case: what if the tag is empty?","دو چیز. اول یک حالت خاص: اگر تگ خالی باشد چه؟"],
["B","Good catch. I'll add a validation check.","نکته خوبی بود. یک بررسی اعتبارسنجی اضافه می‌کنم."],
["A","Second, just a nitpick: use snake_case for all variables.","دوم، فقط یک ایراد جزئی: برای همه متغیرها snake_case بگذار."],
["B","Sure, I'll refactor the naming today.","حتماً، امروز نام‌گذاری را بازآرایی می‌کنم."],
["A","Then I'll approve it. Ping me when it's ready.","بعدش تأییدش می‌کنم. آماده شد خبرم کن."],
["B","Will do. Thanks for the careful review.","حتماً. ممنون بابت بازبینی دقیق."]]},

{ t:"نگارش مستندات و گزارش", en:"Documentation & Reports",
v:[["summary","خلاصه"],["appendix","پیوست"],["assumption","فرض"],["methodology","روش‌شناسی"],["finding","یافته"],["conclusion","نتیجه‌گیری"],["reference","مرجع"],["draft","پیش‌نویس"]],
p:[["The executive summary should be one page maximum.","خلاصه مدیریتی حداکثر باید یک صفحه باشد."],["I documented all assumptions in section two.","همه فرض‌ها را در بخش دو مستند کردم."],["Our main finding is a strong link between heat and failures.","یافته اصلی ما ارتباط قوی گرما و خرابی‌هاست."],["The methodology section explains the data sources.","بخش روش‌شناسی منابع داده را توضیح می‌دهد."],["Detailed tables are in the appendix.","جدول‌های تفصیلی در پیوست هستند."],["I'll share the draft for your comments tomorrow.","فردا پیش‌نویس را برای نظرات شما می‌فرستم."]],
d:[["A","The client wants a written report, not just the dashboard.","مشتری گزارش مکتوب می‌خواهد، نه فقط داشبورد."],
["B","Understood. I'll structure it in four sections.","متوجه شدم. آن را در چهار بخش ساختار می‌دهم."],
["A","Which sections?","کدام بخش‌ها؟"],
["B","Summary, methodology, findings, and recommendations.","خلاصه، روش‌شناسی، یافته‌ها و توصیه‌ها."],
["A","Keep the summary short. Managers won't read ten pages.","خلاصه را کوتاه نگه دار. مدیران ده صفحه نمی‌خوانند."],
["B","Agreed. One page, with three key numbers highlighted.","موافقم. یک صفحه، با سه عدد کلیدی برجسته."],
["A","When can I see a draft?","کی می‌توانم پیش‌نویس را ببینم؟"],
["B","Thursday morning, your time.","پنجشنبه صبح، به وقت شما."]]},

{ t:"مصاحبه شغلی — بخش اول", en:"Job Interviews I: Your Story",
v:[["strength","نقطه قوت"],["weakness","نقطه ضعف"],["achievement","دستاورد"],["challenge","چالش"],["motivated","باانگیزه"],["team player","اهل کار تیمی"],["adapt","سازگار شدن"],["career goal","هدف شغلی"]],
p:[["Tell me about yourself.","درباره خودتان بگویید."],["My greatest strength is turning raw data into decisions.","بزرگ‌ترین قوتم تبدیل داده خام به تصمیم است."],["A key achievement was cutting reporting time by ninety percent.","یک دستاورد کلیدی، کاهش ۹۰ درصدی زمان گزارش‌دهی بود."],["I adapt quickly to new tools and environments.","سریع با ابزارها و محیط‌های جدید سازگار می‌شوم."],["My career goal is to lead a remote analytics team.","هدف شغلی‌ام رهبری یک تیم تحلیل داده ریموت است."],["Why do you want to work with us?","چرا می‌خواهید با ما کار کنید؟"]],
d:[["A","Thanks for joining. Tell me a bit about yourself.","ممنون که آمدید. کمی درباره خودتان بگویید."],
["B","Sure. I'm a data engineer with ten years in petrochemicals.","حتماً. مهندس داده‌ام با ده سال سابقه در پتروشیمی."],
["B","I build predictive maintenance systems and BI dashboards.","سامانه‌های نگهداشت پیش‌بینانه و داشبورد BI می‌سازم."],
["A","What's an achievement you're proud of?","دستاوردی که به آن افتخار می‌کنید چیست؟"],
["B","I automated a plant-wide reliability report, saving days of work.","گزارش قابلیت اطمینان کل کارخانه را خودکار کردم و روزها کار صرفه‌جویی شد."],
["A","And why are you interested in remote work?","و چرا به کار ریموت علاقه دارید؟"],
["B","I want to work with global teams and grow beyond one plant.","می‌خواهم با تیم‌های جهانی کار کنم و فراتر از یک کارخانه رشد کنم."],
["A","Great answer. Let's move to technical questions.","پاسخ خوبی بود. برویم سراغ سؤالات فنی."]]},

{ t:"مصاحبه شغلی — بخش دوم", en:"Job Interviews II: Technical & Behavioral",
v:[["walk me through","قدم‌به‌قدم توضیح بده"],["trade-off","بده‌بستان"],["under pressure","تحت فشار"],["prioritize","اولویت‌بندی کردن"],["conflict","تعارض / اختلاف"],["outcome","نتیجه"],["approach","رویکرد"],["lesson learned","درس آموخته‌شده"]],
p:[["Walk me through your approach to a new dataset.","رویکردت به یک دیتاست جدید را قدم‌به‌قدم توضیح بده."],["First I profile the data, then I check for quality issues.","اول داده را پروفایل می‌کنم، بعد مشکلات کیفیت را بررسی می‌کنم."],["Tell me about a time you worked under pressure.","از زمانی بگو که تحت فشار کار کردی."],["The outcome was positive: we met the deadline.","نتیجه مثبت بود: به مهلت رسیدیم."],["The lesson learned was to validate assumptions early.","درس آموخته‌شده این بود که فرض‌ها را زود اعتبارسنجی کنم."],["How do you prioritize when everything is urgent?","وقتی همه‌چیز فوری است چطور اولویت‌بندی می‌کنی؟"]],
d:[["A","Tell me about a difficult technical problem you solved.","از یک مشکل فنی سخت بگویید که حلش کردید."],
["B","Sure. Our report server kept failing after a system upgrade.","حتماً. سرور گزارش ما بعد از یک ارتقا مدام از کار می‌افتاد."],
["A","How did you approach it?","چطور با آن برخورد کردید؟"],
["B","I isolated variables one by one: services, logs, then the database.","متغیرها را یکی‌یکی جدا کردم: سرویس‌ها، لاگ‌ها، بعد دیتابیس."],
["B","The root cause was a permissions change nobody documented.","علت ریشه‌ای تغییر دسترسی‌ای بود که کسی مستند نکرده بود."],
["A","What was the outcome?","نتیجه چه شد؟"],
["B","Full recovery in one day, plus a new change-log process.","بازیابی کامل در یک روز، به‌علاوه یک فرایند جدید ثبت تغییرات."],
["A","Excellent example of structured thinking.","نمونه عالی از تفکر ساختاریافته."]]},

{ t:"مذاکره حقوق و قرارداد", en:"Salary & Contract Negotiation",
v:[["compensation","حقوق و مزایا"],["rate","نرخ (ساعتی/پروژه‌ای)"],["negotiable","قابل مذاکره"],["benefits","مزایا"],["contract","قرارداد"],["hourly","ساعتی"],["market rate","نرخ بازار"],["counteroffer","پیشنهاد متقابل"]],
p:[["What's your expected compensation?","حقوق مورد انتظار شما چقدر است؟"],["Based on market rates, I'm looking at forty dollars per hour.","بر اساس نرخ بازار، دنبال ساعتی چهل دلار هستم."],["Is the rate negotiable?","نرخ قابل مذاکره است؟"],["Could you share the full contract terms?","می‌شود شرایط کامل قرارداد را بفرستید؟"],["I'd like to make a counteroffer.","می‌خواهم یک پیشنهاد متقابل بدهم."],["Payment terms matter as much as the rate.","شرایط پرداخت به اندازه نرخ اهمیت دارد."]],
d:[["A","We'd like to offer you the contract. Let's discuss terms.","می‌خواهیم قرارداد را به شما پیشنهاد دهیم. درباره شرایط صحبت کنیم."],
["B","Great news. What rate do you have in mind?","خبر خوبی است. چه نرخی مدنظر دارید؟"],
["A","We budgeted thirty dollars per hour for this role.","برای این نقش ساعتی سی دلار بودجه گذاشته‌ایم."],
["B","I appreciate the offer. Based on my experience, I was expecting forty.","ممنون از پیشنهاد. با توجه به تجربه‌ام، انتظار چهل داشتم."],
["A","That's above our budget. Could we meet at thirty-five?","بالاتر از بودجه ماست. می‌شود روی سی‌وپنج توافق کنیم؟"],
["B","Thirty-five works if we review it after three months.","سی‌وپنج قبول است اگر بعد از سه ماه بازنگری شود."],
["A","Deal. I'll add the review clause to the contract.","قبول. بند بازنگری را به قرارداد اضافه می‌کنم."],
["B","Perfect. Please send it over and I'll sign this week.","عالی. لطفاً بفرستید، همین هفته امضا می‌کنم."]]},

{ t:"ظرافت‌های فرهنگی و ادب", en:"Cultural Nuances & Politeness",
v:[["polite","مؤدبانه"],["direct","مستقیم / رک"],["formal","رسمی"],["casual","غیررسمی / خودمانی"],["would you mind","اشکالی ندارد اگر"],["I'd appreciate it","ممنون می‌شوم"],["with all due respect","با کمال احترام"],["small favor","لطف کوچک"]],
p:[["Would you mind sending that file again?","اشکالی ندارد آن فایل را دوباره بفرستید؟"],["I'd appreciate it if you could reply by Friday.","ممنون می‌شوم اگر تا جمعه پاسخ دهید."],["Sorry to bother you, but I have a quick question.","ببخشید مزاحم می‌شوم، یک سؤال سریع دارم."],["With all due respect, I see it differently.","با کمال احترام، من طور دیگری می‌بینم."],["No worries, take your time.","مشکلی نیست، عجله نکنید."],["Thanks a lot, that really helps.","خیلی ممنون، واقعاً کمک می‌کند."]],
d:[["A","Quick question: is it rude to say 'no' directly in your culture?","سؤال سریع: در فرهنگ شما «نه» مستقیم گفتن بی‌ادبی است؟"],
["B","Often we soften it. We might say 'let me check' first.","اغلب نرمش می‌کنیم. شاید اول بگوییم «بگذار بررسی کنم»."],
["A","Interesting. In our team, direct is considered efficient.","جالب است. در تیم ما، مستقیم بودن نشانه کارایی است."],
["B","Good to know. I'll be more direct in our calls then.","خوب است بدانم. پس در تماس‌ها مستقیم‌تر خواهم بود."],
["A","And please tell me if I ever sound too blunt.","و لطفاً بگو اگر من زیادی رک به نظر رسیدم."],
["B","Deal. Clear communication beats guessing.","قبول. ارتباط شفاف بهتر از حدس زدن است."],
["A","Exactly. That's how remote teams survive.","دقیقاً. تیم‌های ریموت این‌طور دوام می‌آورند."],
["B","Agreed. Thanks for the open conversation.","موافقم. ممنون بابت گفت‌وگوی باز."]]},

{ t:"مکالمات دشوار و حل تعارض", en:"Difficult Conversations",
v:[["misunderstanding","سوءتفاهم"],["concern","نگرانی"],["address","رسیدگی کردن به"],["apologize","عذرخواهی کردن"],["take responsibility","مسئولیت پذیرفتن"],["move forward","به جلو حرکت کردن"],["constructive","سازنده"],["resolve","حل‌وفصل کردن"]],
p:[["I think there's been a misunderstanding.","فکر می‌کنم سوءتفاهمی پیش آمده."],["I'd like to address a concern about the timeline.","می‌خواهم به نگرانی‌ای درباره زمان‌بندی رسیدگی کنم."],["I apologize for the delay. It was my mistake.","بابت تأخیر عذرخواهی می‌کنم. اشتباه من بود."],["I take full responsibility for the error.","مسئولیت کامل خطا را می‌پذیرم."],["Let's focus on how to move forward.","بیایید روی راه پیش رو تمرکز کنیم."],["I want to resolve this constructively.","می‌خواهم این را سازنده حل کنیم."]],
d:[["A","Sadegh, the client says the report had wrong numbers.","صادق، مشتری می‌گوید گزارش اعداد اشتباه داشت."],
["B","I heard. I checked, and yes, one filter was misconfigured.","شنیدم. بررسی کردم و بله، یک فیلتر اشتباه تنظیم شده بود."],
["B","I take responsibility. It was my oversight.","مسئولیتش را می‌پذیرم. غفلت من بود."],
["A","I appreciate the honesty. How do we fix it?","صداقتت را قدر می‌دانم. چطور درستش کنیم؟"],
["B","The corrected report is ready. I'll also add an automated check.","گزارش اصلاح‌شده آماده است. یک بررسی خودکار هم اضافه می‌کنم."],
["A","Good. Should we tell the client together?","خوب. با هم به مشتری بگوییم؟"],
["B","Yes, I'll draft an honest, short explanation for the call.","بله، یک توضیح صادقانه و کوتاه برای تماس آماده می‌کنم."],
["A","Perfect. Mistakes happen; recovery is what matters.","عالی. اشتباه پیش می‌آید؛ مهم جبران است."]]},

{ t:"جمع‌بندی: مصاحبه و ارائه نهایی", en:"Capstone: Mock Interview & Presentation",
v:[["portfolio","نمونه‌کار"],["case study","مطالعه موردی"],["impact","تأثیر"],["metric","سنجه / متریک"],["end-to-end","سرتاسری"],["ownership","مالکیت / تعهد کامل"],["scalable","مقیاس‌پذیر"],["next steps","گام‌های بعدی"]],
p:[["Let me present a case study from my portfolio.","اجازه دهید یک مطالعه موردی از نمونه‌کارم ارائه کنم."],["I owned this project end-to-end.","این پروژه را سرتاسری بر عهده داشتم."],["The impact: downtime costs dropped by thirty percent.","تأثیرش: هزینه‌های توقف ۳۰ درصد کاهش یافت."],["The solution is scalable to other plants.","راه‌حل به کارخانه‌های دیگر مقیاس‌پذیر است."],["I measure success with three clear metrics.","موفقیت را با سه سنجه روشن اندازه می‌گیرم."],["As next steps, I'd suggest a two-week pilot.","به‌عنوان گام بعدی، یک پایلوت دوهفته‌ای پیشنهاد می‌کنم."]],
d:[["A","Final round. Present one project as if I'm the client.","دور نهایی. یک پروژه را طوری ارائه کن که انگار من مشتری‌ام."],
["B","Gladly. The problem: unplanned valve failures cost us millions.","با کمال میل. مسئله: خرابی‌های ناگهانی شیرها میلیون‌ها هزینه داشت."],
["B","My solution: a reliability system connecting CMMS data to dashboards.","راه‌حل من: سامانه‌ای که داده CMMS را به داشبورد متصل می‌کند."],
["B","I owned it end-to-end: data model, ETL, and the final reports.","سرتاسری بر عهده داشتم: مدل داده، ETL و گزارش‌های نهایی."],
["A","How do you prove the impact?","تأثیر را چطور اثبات می‌کنی؟"],
["B","Three metrics: MTBF up 22%, reporting time down 90%, zero missed inspections.","سه سنجه: MTBF ‏۲۲٪ بالا، زمان گزارش ۹۰٪ پایین، صفر بازرسی ازدست‌رفته."],
["A","Convincing. If we hire you, what are your first steps?","قانع‌کننده است. اگر استخدامت کنیم، اولین گام‌هایت چیست؟"],
["B","Week one: listen and map your data. Week two: a quick win pilot.","هفته اول: شنیدن و نگاشت داده شما. هفته دوم: یک پایلوت با نتیجه سریع."]]},
];

// ---- معاشرت روزانه: everyday social exchanges, rotating by date ----
const SOCIAL = [
["How's your day going so far?","Pretty good, thanks. A bit busy, but no complaints.","روزت تا الان چطور می‌گذرد؟ — خوب است، ممنون. کمی شلوغ، ولی راضی‌ام."],
["Did you do anything fun over the weekend?","Yes, I had dinner with my family. It was really nice.","آخر هفته کار جالبی کردی؟ — بله، با خانواده شام رفتیم. خیلی خوب بود."],
["What do you usually do after work?","I usually go for a walk and then relax at home.","بعد از کار معمولاً چه می‌کنی؟ — معمولاً پیاده‌روی می‌کنم و بعد در خانه استراحت."],
["Have you tried any good food lately?","Yes! I found a great kebab place near my home.","اخیراً غذای خوبی امتحان کرده‌ای؟ — بله! یک کبابی عالی نزدیک خانه پیدا کردم."],
["How do you like your coffee?","Strong, with no sugar. I need it in the morning!","قهوه‌ات را چطور دوست داری؟ — غلیظ و بدون شکر. صبح‌ها لازمش دارم!"],
["Any plans for the holidays?","Probably a short trip to the north with friends.","برنامه‌ای برای تعطیلات داری؟ — احتمالاً یک سفر کوتاه به شمال با دوستان."],
["What kind of music do you listen to?","Mostly traditional music, but sometimes rock too.","چه نوع موسیقی گوش می‌دهی؟ — بیشتر سنتی، ولی گاهی راک هم."],
["Do you play any sports?","I swim twice a week. It clears my mind.","ورزشی انجام می‌دهی؟ — هفته‌ای دو بار شنا می‌کنم. ذهنم را آزاد می‌کند."],
["How was the traffic this morning?","Terrible, as usual! It took me an hour.","ترافیک امروز صبح چطور بود؟ — افتضاح، مثل همیشه! یک ساعت طول کشید."],
["Are you a morning person or a night owl?","Definitely a night owl. Mornings are hard for me.","سحرخیزی یا شب‌زنده‌دار؟ — قطعاً شب‌زنده‌دار. صبح‌ها برایم سخت است."],
["What's the weather like there today?","Sunny and very hot. Typical summer here.","هوای آنجا امروز چطور است؟ — آفتابی و خیلی گرم. تابستان معمولی اینجا."],
["Did you watch anything good recently?","Yes, a documentary about the ocean. Amazing!","اخیراً چیز خوبی تماشا کرده‌ای؟ — بله، یک مستند درباره اقیانوس. فوق‌العاده!"],
["How's your family doing?","Everyone's well, thanks for asking.","خانواده چطورند؟ — همه خوب‌اند، ممنون که پرسیدی."],
["What do you do to relax?","Reading and a cup of tea. Simple but effective.","برای آرامش چه می‌کنی؟ — کتاب و یک فنجان چای. ساده ولی مؤثر."],
["Any exciting news this week?","Actually yes, my brother got a new job!","خبر هیجان‌انگیزی این هفته هست؟ — راستش بله، برادرم کار جدید گرفت!"],
["Do you enjoy cooking?","I do! My specialty is rice with saffron.","آشپزی دوست داری؟ — بله! تخصصم برنج با زعفران است."],
["How long is your commute?","About forty minutes each way by car.","رفت‌وآمدت چقدر طول می‌کشد؟ — حدود چهل دقیقه هر طرف با ماشین."],
["What are you reading these days?","A book about habits. Very practical.","این روزها چه می‌خوانی؟ — کتابی درباره عادت‌ها. خیلی کاربردی."],
["Do you have any pets?","No, but I'd love to have a cat someday.","حیوان خانگی داری؟ — نه، ولی دوست دارم روزی یک گربه داشته باشم."],
["What's your favorite season?","Autumn, definitely. The weather is perfect.","فصل مورد علاقه‌ات چیست؟ — قطعاً پاییز. هوا عالی است."],
["Long time no see! How have you been?","I know, it's been a while! I've been great.","خیلی وقت است ندیدمت! چطور بودی؟ — آره، مدتی گذشته! عالی بودم."]];

// ---- resume personalization: known skills and phrase templates ----
const SKILL_BANK = ["power bi","sql","python","excel","etl","dax","power query","dashboard","reporting","data analysis","data engineering","machine learning","predictive","maintenance","reliability","cmms","kpi","iot","pandas","numpy","networking","ccna","project management","asset management","automation","visualization","database","petrochemical","rotating equipment","vibration","leadership","teamwork"];
const SKILL_TPL = [
["I have hands-on experience with {s}.","با {s} تجربه عملی دارم."],
["In my last role, I used {s} to solve real business problems.","در نقش قبلی‌ام از {s} برای حل مسائل واقعی استفاده کردم."],
["One of my core strengths is {s}.","یکی از قوت‌های اصلی من {s} است."],
["I've delivered several projects involving {s}.","چند پروژه مرتبط با {s} تحویل داده‌ام."],
["I'm confident discussing {s} in technical interviews.","در مصاحبه‌های فنی با اطمینان درباره {s} صحبت می‌کنم."]];
